server:
  port: 8888

spring:
  application:
    name: micro-admin-config-server
    
  profiles:
    active: native
    
  cloud:
    config:
      server:
        native:
          search-locations: C:\Diseño de soluciones\Wordspace-certus\ms-gestion-config-data\ms-gestion-config-data
